# Postgres database development settings
development:
  adapter: postgresql
  encoding: unicode
  database: bucketlist_api_dev
  pool: 5
  username: root
  password: root
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  username: root
  password: root
  

production:
  adapter: postgresql
  encoding: unicode
  database: bucketlist_api
  pool: 5
  username: root
  password: root